### ISSUE TITLE
[Side Navigation] Name and Address form templates do not have headers and scroll to the wrong point in the browser when using sidenav

### ISSUE THREAD

**Issue by jpyuda** [18F/web-design-standards#467]
It scrolls to a random-seeming point (see below)

<img width="991" alt="screen shot 2015-09-09 at 4 31 03 pm" src="https://cloud.githubusercontent.com/assets/552095/9773441/35bea086-5710-11e5-8f5a-959977cee508.png">

This may be because there are not currently headers for those forms (which there should be)

**Comment by maya** [comment]
Also there are no headings on those "cut off" components. Do we want our forms to be consistent and everything to have headings. Right now some do and some don't. The reason we did that originally was bc we have the name of it already within the form itself via the legend. cc @mollieru

**Comment by carodew** [comment]
@maya yeah, we did make that decision, although without realizing this implication. 

There's another wrinkle – we have intro text for each individual form template that is supposed to go right under the header for each one. I can easily plop that in myself, but for the two forms that don't have a header it's a little trickier. I'll bring this up again in bug triage today.

**Comment by carodew** [comment]
From bug triage – I'm going to go in and add headers when I go in and add intro text (which I have to do anyway). Will check when done to see if this fixes the jump issue. We can discuss later if the headers seem duplicative (it might be different now given the different header styles).

**Comment by maya** [comment]
@carodew Ok and just to let you know @vgvg is currently working on this issue in order to get proper spacing back when you click on it.

**Comment by carodew** [comment]
@vgvg Will my adding headers and intro content in screw this up?

**Comment by maya** [comment]
@carodew if you follow the conventions from the rest, I don't think it should, but we can always test when he has the fix.

**Comment by carodew** [comment]
kk. So should I move the `id` up to the `h2`, and remove it from the preview div?

e.g. 

`<div class="preview" id="name-form">`

turns into 

`<h2 class="usa-heading" id="name-form">Name form</h2>`
`<div class="preview">`

**Comment by carodew** [comment]
Anyway – see PR #485

**Comment by maya** [comment]
Fixed in https://github.com/18F/web-design-standards/pull/496 @jpyuda @carodew

**Comment by carodew** [comment]
I'm still experiencing the issue. I think there are some other PRs that need to be merged in before we can close this, see thread above.

**Comment by maya** [comment]
@carodew which PRs?

**Comment by carodew** [comment]
NM – it is working for me now. Closing!
